name: Kernel Build via Script with Cached Neutron Clang

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    
    
    

    
    - name: Make build.sh executable
      run: chmod +x build.sh

    - name: Run build script
      run: |
        ./build.sh

    - name: Upload built Image
      uses: actions/upload-artifact@v4
      with:
        name: kernel-image
        path: build/Image
